name: Deploy CiCd-deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          script_stop: true
          script: |
            cd /var/www
            ls -al
            rm -rf cicd-deploy
            git clone https://github.com/AnDong4213/cicd-deploy.git -b ${{ github.ref_name }}
            cd cicd-deploy
            npm install --registry=https://registry.npmmirror.com
            npm run build
